/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Campaign = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'sentAt' : IDL.Int,
  'recipientCount' : IDL.Nat,
});
export const Subscriber = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
export const CampaignInput = IDL.Record({
  'subject' : IDL.Text,
  'body' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSubscriber' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCampaignsSent' : IDL.Nat,
          'totalSubscribers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'listSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
  'removeSubscriber' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendCampaign' : IDL.Func([CampaignInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Campaign = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'sentAt' : IDL.Int,
    'recipientCount' : IDL.Nat,
  });
  const Subscriber = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const CampaignInput = IDL.Record({ 'subject' : IDL.Text, 'body' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSubscriber' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCampaignsSent' : IDL.Nat,
            'totalSubscribers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'listSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
    'removeSubscriber' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendCampaign' : IDL.Func([CampaignInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };